// <auto-generated />
namespace Controllers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _03072018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03072018));
        
        string IMigrationMetadata.Id
        {
            get { return "201807040043419_03-07-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
